%why is the distance generated by sdp_cons for the test3 example higher
%than the same problem worked out in local search?
%
%that makes no sense. the sdp should be a lower bound.
%
%very likely there are extra constraints added in the sdp

%% load data
load('test3_data.mat');
load('test3_derived.mat');

n = length(phi{1});
m = length(phi);
n_ineq = size(Asdp, 1);

%% local search (fmincon) solution
%using yalmip in order to get the dual variables
% [func_bound, selector, vars] = cons_local_yalmip_model(y, Q, phi, Asdp, bsdp, Aeqsdp, beqsdp);

%take the alpha acquired from fmincon

x = sdpvar(n, 1);
quad_cons = [Asdp*x <= bsdp];
quad_obj = zeros(1, 1, 'like', sdpvar);
for j = 1:m
    quad_obj = quad_obj + alpha_con(j)*(0.5*x'*Q{j}*x + phi{j}'*x);
end
opts = sdpsettings('solver', 'mosek');
sol = optimize(quad_cons, quad_obj, opts);

x_rec = value(x);
mu_rec = dual(quad_cons);

%package up the data into a moment matrix
v = [1; x_rec; alpha_con; mu_rec];

M_local = v*v';

dist_local_again = norm(x_rec - y, 2);

