%why is the distance generated by sdp_cons for the test3 example higher
%than the same problem worked out in local search?
%
%that makes no sense. the sdp should be a lower bound.
%
%very likely there are extra constraints added in the sdp

%% load data
load('test3_data.mat');
load('test3_derived.mat');

bound = 2.89; %dual infeasible. this means that this bound is too large?

% bound = 3;


input = struct('y', y, ...
    'A', Asdp, 'b', bsdp, 'Aeq', Aeqsdp, 'beq', beqsdp, 'cons', 1);

input.y = y;
input.Q = Q;
input.f=phi;
 [dist_rec, info] = reweight_single(input, bound);